name: GCMS Playwright Automation

on:
  schedule:
    - cron: "0 21 * * 5"   # sexta-feira 18:00 (UTC-3)
  workflow_dispatch:        # permite rodar manualmente

jobs:
  run-gcms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run script
        env:
          GCMS_URL: "https://unifier.oraclecloud.com/alcoa/bp/route/home/i-unifier"
          PROJETO_CSV: "Lista de Projetos.csv"
        run: |
          python src/main.py
